name: Build RicePi .deb package

on:
  push:
    branches:
      - ricepi/main
  pull_request:
    branches:
      - ricepi/main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/RaspberryRetards/ricepi

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dh-python

      - name: Build .deb package
        run: |
          cd ricepi
          dpkg-deb --build .
          mv ricepi*.deb ../artifact.deb

      - name: Upload .deb as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: ricepi-deb
          path: artifact.deb
