name: Build RicePi .deb package

on:
  push:
    branches:
      - ricepi/main
  pull_request:
    branches:
      - ricepi/main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packaging tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-python

    - name: Build .deb package
      run: |
        cd ricepi  # Navigate to the folder where the deb package structure exists
        dpkg-deb --build ricepi artifact.deb

    - name: Upload .deb as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: ricepi-deb-package
        path: ricepi/artifact.deb
