name: Build RicePi .deb package

on:
  push:
    branches:
      - ricepi/main
  pull_request:
    branches:
      - ricepi/main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper dh-python

      - name: Build .deb package
        run: |
          cd ricepi
          dpkg-deb --build ricepi ricepi.deb
          ls -l 

      - name: Move .deb file to artifact location
        run: |
          mv ricepi*.deb ../artifact.deb

      - name: Upload .deb as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ricepi-deb
          path: artifact.deb
